controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # position_controller:
    #   type: position_controllers/JointGroupPositionController
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      - robot/link_joint1
      - robot/link_joint11
      - robot/link_joint2
      - robot/link_joint22
    
    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity
